#--------------------------------------------------------------
# functions to create a signal to test the detections on 
#--------------------------------------------------------------
import numpy as np


def insert_pvc(ecg, fs, pvc_time_sec, amp_factor=2.0, width_factor=2.0):
    """
    Insert a synthetic premature ventricular contraction (PVC) into a raw ECG signal.

    The function extracts a short QRS-complex template from the input ECG,
    amplifies and stretches it, and then adds the resulting waveform at a
    user-specified time point. This is useful for creating controlled test
    data when developing or benchmarking R-peak detection, arrhythmia-
    detection, or online changepoint-detection pipelines.

    Parameters
    ----------
    ecg : np.ndarray
        One-dimensional array containing the raw ECG voltage values (e.g. µV or mV).
        The signal should be sampled uniformly at the rate given by ``fs``.
    fs : int or float
        Sampling frequency of ``ecg`` in Hertz (samples per second).
    pvc_time_sec : float
        Desired onset time of the synthetic PVC, expressed in seconds from the
        start of the signal.  The function will centre the PVC waveform around
        this time point.
    amp_factor : float, optional (default=2.0)
        Multiplicative factor applied to the amplitude of the extracted QRS
        template.  Larger values produce a taller PVC spike, mimicking the
        higher voltage often observed in ectopic beats.
    width_factor : float, optional (default=2.0)
        Stretch factor applied to the temporal width of the template.  The
        template is linearly interpolated to ``len(template) * width_factor``.
        A value >1 makes the PVC broader (wider QRS complex), while a value
        <1 would compress it.

    Returns
    -------
    np.ndarray
        A copy of ``ecg`` with the synthetic PVC added.  The original ``ecg``
        array is **not** modified in-place.

    Notes
    -----
    * **Template selection** The function uses ``scipy.signal.find_peaks`` to
      locate the first prominent peak in the ECG (assumed to be a normal QRS
      complex) and extracts a symmetric window of ``0.4s`` (±0.2s) around it.
      If the ECG does not contain a clear peak (e.g., a very flat signal) the
      function will raise an ``IndexError``.
    * **Boundary handling** When the PVC would extend beyond the start or end
      of the signal, the waveform is truncated so that it fits exactly within
      the available data range.
    * **Additive injection** The PVC is added to the existing signal
      (``ecg_mod[start:end] += pvc_wave``).  Consequently, the resulting
      amplitude is the sum of the original ECG and the synthetic PVC.  If a
      purely replacement is desired, replace the ``+=`` with ``=``.
    * **Physiological realism** The synthetic PVC generated by this routine
      is a simple scaled and stretched copy of a normal QRS.  Real PVCs often
      exhibit altered morphology (different polarity, notches, etc.).  For
      more realistic simulations consider using a dedicated ECG synthesis
      library (e.g., `ECGSyn` or `NeuroKit2.ecg_simulate`).

    Examples
    --------
    >>> import wfdb, numpy as np
    >>> rec = wfdb.rdrecord('100', pn_dir='mitdb')
    >>> fs = rec.fs
    >>> raw_ecg = rec.p_signal[:, 0]               # Lead II
    >>> # Insert a PVC at 30 seconds with doubled amplitude and width
    >>> ecg_with_pvc = insert_pvc(raw_ecg, fs, pvc_time_sec=30.0,
    ...                          amp_factor=2.0, width_factor=2.0)
    >>> # Plot a short segment to visualise the PVC
    >>> import matplotlib.pyplot as plt
    >>> t = np.arange(len(ecg_with_pvc)) / fs
    >>> plt.plot(t[29000:31000], ecg_with_pvc[29000:31000])
    >>> plt.axvline(30, color='red', linestyle='--')
    >>> plt.show()
    """
    from scipy.signal import find_peaks
    peaks, _ = find_peaks(ecg, distance=int(0.5 * fs))
    template_center = peaks[0]
    half_len = int(0.2 * fs)
    template = ecg[template_center - half_len:template_center + half_len]
    template = template * amp_factor
    new_len = int(len(template) * width_factor)
    pvc_wave = np.interp(np.linspace(0, len(template)-1, new_len),
                         np.arange(len(template)), template)
    insert_idx = int(pvc_time_sec * fs)
    start = max(insert_idx - new_len // 2, 0)
    end = start + new_len
    if end > len(ecg):
        pvc_wave = pvc_wave[:len(ecg)-start]
        end = len(ecg)
    ecg_mod = ecg.copy()
    ecg_mod[start:end] += pvc_wave
    return ecg_mod

def bandpass(sig, low=0.5, high=40.0, fs=250, order=2):
    """
    Apply a Butterworth band-pass filter to a one-dimensional signal.

    The filter attenuates frequencies outside the pass-band
    ``[low, high]``Hz while preserving the phase of the original signal
    (zero-phase filtering is achieved with ``scipy.signal.filtfilt``).

    Parameters
    ----------
    sig : array_like
        Input signal to be filtered.  Typically a 1D NumPy array containing
        voltage values (e.g., µV or mV) sampled uniformly at ``fs``Hz.
    low : float, optional
        Lower cutoff frequency of the pass-band in Hertz.  Frequencies
        below this value are strongly attenuated.  Default is ``0.5 Hz``,
        which removes very low-frequency baseline wander.
    high : float, optional
        Upper cutoff frequency of the pass-band in Hertz.  Frequencies
        above this value are strongly attenuated.  Default is ``40.0 Hz``,
        which removes high-frequency noise while preserving the QRS
        complex in typical ECG recordings.
    fs : float or int, optional
        Sampling frequency of ``sig`` in Hertz.  The Nyquist frequency is
        computed as ``fs/2`` and used to normalise the cutoff frequencies.
        Default is ``250Hz`` (a common ECG acquisition rate).
    order : int, optional
        Order of the Butterworth filter.  Higher orders give a steeper
        roll-off but can introduce ringing if the filter becomes too sharp.
        A second-order filter (default) provides a good trade-off between
        attenuation and waveform preservation for most biomedical signals.

    Returns
    -------
    ndarray
        The filtered signal, having the same shape as ``sig``.  Because
        ``filtfilt`` performs forward and backward-filtering, the output
        has zero phase distortion and no group delay.

    """
    nyq = 0.5 * fs
    b, a = butter(order, [low / nyq, high / nyq], btype='band')
    return filtfilt(b, a, sig)

